rolsac.target=dgtic-rolsac
project.author=CAIB-DGTIC-ABASTOS

# Directori de deploy
deploy.dir=C:\\caib\\aplicacions\\jboss-5.2-gusite-des\\server\\jboss05\\deploycaib
jbossServiceDeploy.dir=C:\\caib\\aplicacions\\jboss-5.2-gusite-des\\server\\jboss05\\deploycaib

# SVN
mvn.repository.path=C:\\Users\\u93187\\.m2\\repository\\

# Log del sql generado
hibernate.show_sql=false