-- 
ALTER TABLE GUS_SOLJOB ADD JOB_IDELEM NUMBER(19,0);
COMMENT ON COLUMN "GUS_SOLJOB"."JOB_IDELEM" IS 'Identificador del id elemento, microsite/ua';

-- INDICES SOBRE LAS ENCUESTAS PARA SOLVENTAR PROBLEMAS DE RENDIMIENTO
CREATE INDEX "GUS_ENCUST_ENC_MICCOD_FK_I" ON "GUS_ENCUST" ("ENC_MICCOD");
CREATE INDEX "GUS_PREGUN_PRE_ENCCOD_FK_I" ON "GUS_PREGUN" ("PRE_ENCCOD");
CREATE INDEX "GUS_RESPUS_RES_PRECOD_FK_I" ON "GUS_RESPUS" ("RES_PRECOD");
CREATE INDEX "GUS_ENCVOT_VOT_IDRESP_FK_I" ON "GUS_ENCVOT" ("VOT_IDRESP");
CREATE INDEX "GUS_ENCVOT_VOT_IDENCU_I" ON "GUS_ENCVOT" ("VOT_IDENCU");
CREATE INDEX "GUS_ENCVOT_VOT_IDPREG_I" ON "GUS_ENCVOT" ("VOT_IDPREG");
CREATE INDEX "GUS_ENCVOT_VOT_CODUSU_I" ON "GUS_ENCVOT" ("VOT_CODUSU");