GRANT INSERT, SELECT, DELETE, UPDATE ON GUS_AUDITORIA TO WWW_GUSITE;
GRANT INSERT, SELECT, DELETE, UPDATE ON GUS_FR_TEMA TO WWW_GUSITE;
GRANT INSERT, SELECT, DELETE, UPDATE ON GUS_FR_PLANTILLA TO WWW_GUSITE;
GRANT INSERT, SELECT, DELETE, UPDATE ON GUS_FR_VERSION TO WWW_GUSITE;
GRANT INSERT, SELECT, DELETE, UPDATE ON GUS_FR_TEMA TO WWW_GUSITE;
GRANT INSERT, SELECT, DELETE, UPDATE ON GUS_FR_PERPLA TO WWW_GUSITE;
GRANT INSERT, SELECT, DELETE, UPDATE ON GUS_FR_ARCHIVO TO WWW_GUSITE;

GRANT SELECT ON "GUS_SEQAUD" TO WWW_GUSITE;
GRANT SELECT ON "GUS_SEQFTE" TO WWW_GUSITE;
GRANT SELECT ON "GUS_SEQPLA" TO WWW_GUSITE;
GRANT SELECT ON "GUS_SEQFVE" TO WWW_GUSITE;
GRANT SELECT ON "GUS_SEQPPL" TO WWW_GUSITE;
GRANT SELECT ON "GUS_SEQARC" TO WWW_GUSITE;

